#!/bin/bash
# Glibc for various OS: https://gist.github.com/wagenet/35adca1a032cec2999d47b6c40aa45b1
# https://distrowatch.com/table.php?distribution=redhat
# RHEL 8 : glibc 2.28
# RHEL 9 : glibc 2.34
# https://distrowatch.com/table.php?distribution=ubuntu
# Ubuntu 18.10 cosmic : glibc 2.28
# Ubuntu 20.04 focal : glibc 2.31
# Ubuntu 21.10 impish : gblic 2.34
# https://www.ibm.com/docs/en/ahts/4.4.x?topic=release-notes
# ascp 4.4.5 : gblic 2.28
# dwarfs requires boost >= 1.65
# boost requires cmake >= 3.30
# https://hub.docker.com/search?q=tebako
# https://github.com/tamatebako/tebako-ci-containers
set -ex

if test $# -lt 3; then
    echo "Usage: $0 <CLI_EXECUTABLE> <CLI_NAME> <GEM_SPEC...>" 1>&2
    echo "Env: TMPDIR" 1>&2
    exit 1
fi

CLI_EXECUTABLE=$1
CLI_NAME=$2
shift 2
DIR_TMP=$TMPDIR

echo "Building: $(basename $CLI_EXECUTABLE)"

# tebako compilation
tebako_env=$DIR_TMP/tebako-env
# project files (gem)
tebako_root=$DIR_TMP/tebako-root
# only provide the name, not path
tebako_entry=$CLI_NAME
tebako_output=$CLI_EXECUTABLE

mkdir -p $tebako_env $tebako_root
#(cd $tebako_root && gem fetch $GEM_NAME:$GEM_VERSION && ls -1)
# Pull gem and dependencies
tmp_dir_install=$DIR_TMP/tebako-install
# only main gem and its dependencies
gem install "$1" --no-document --install-dir $tmp_dir_install
# including optional gems
#for spec in "$@"; do gem install "$spec" --no-document --install-dir $tmp_dir_install; done
mv $tmp_dir_install/cache/*.gem $tebako_root
rm -fr $tmp_dir_install
case $(uname -s) in
Darwin)
    brew update
    # install tools
    brew install bash binutils bison flex gnu-sed lz4 pkg-config xz
    # install libs
    brew install boost double-conversion fmt gdbm glog jemalloc libevent libffi libsodium libyaml ncurses openssl@3 zlib
    # make sure tools are reachable
    brew_root=$(brew --prefix)
    export PATH=$brew_root/opt/flex/bin:$brew_root/opt/bison/bin:$PATH
    # remove binutils from path so that macos `ar` is used
    export PATH=$(echo $PATH|tr : \\n|grep -v /binutils/|paste -sd: -)
    gem install tebako
    ;;
Linux)
    #tebako_container_tag=alpine-3.17
    tebako_container_tag=ubuntu-20.04
    tebako_container_version=0.13.4
    local_root=$tebako_root
    tebako_root=/mnt/w
    tebako_prefix="podman run --rm -v $local_root:$tebako_root ghcr.io/tamatebako/tebako-$tebako_container_tag:$tebako_container_version"
    tebako_opts=--patchelf
    tebako_output=$tebako_root/$(basename $CLI_EXECUTABLE)
    ;;
LinuxLocal)
    dnf module reset ruby
    dnf module install ruby:3.3
    dnf install -y cmake git bash sudo autoconf boost-devel flex bison make clang binutils-devel libevent-devel libacl-devel sed python3 pkgconfig curl lz4-devel openssl-devel zlib-devel xz zip unzip tar xz-devel elfutils-devel libffi-devel gdbm-devel ncurses-devel readline-devel ruby-devel gettext-devel brotli-devel clang libxslt-devel
    echo TODO
    exit 1
    dnf install 
    ;;
*)
    echo "This OS is not supported." >&2
    exit 1
    ;;
esac
set -x
exec $tebako_prefix tebako press --root=$tebako_root --entry-point=$tebako_entry --output=$tebako_output --prefix=$tebako_env $tebako_opts
