# Embedded Ruby template
# Lines beginning with "#erb:" are embedded ruby lines.
# Processing is done in Makefile to avoid syntax error in Dockerfile
# @param arg_gem specify a gemfile or a gem version
# @param arg_opt specify list of optional gems
# Review the version of Ruby to be used periodically from :
# https://hub.docker.com/_/ruby
FROM docker.io/ruby:3.4.4-slim
#erb: if arg_gem.end_with?('.gem')
# For beta, gem is file, then copy it.
COPY <%=arg_gem%> .
# If a gem file was provided, once copied in container: use the basename only
#erb: arg_gem=File.basename(arg_gem)
#erb: end
# Location of Aspera SDK files (binaries, license file)
# Install globally, does not need to be in user's home
# Must be outside /home/cliuser/.aspera/ascli which will be a volume
ARG aspera_bin_dir=/ibm_aspera
# set SDK location in container
ENV ASCLI_SDK_FOLDER=$aspera_bin_dir
# Install aspera-cli gem (beta or release), optional gems and other packages
# Install SDK, create key files and check that ascp works
RUN \
  apt-get update && \
  apt-get install -y imagemagick optipng && \
  apt-get clean && \
  rm -fr /var/lib/apt/lists/* && \
  gem install <%=arg_opt%> <%=arg_gem%> && \
  rm -f <%=arg_gem%> && \
  useradd -m -u 1000 -s /bin/bash cliuser && \
  mkdir -p /home/cliuser/.aspera/ascli && \
  chown -R cliuser: /home/cliuser && \
  mkdir -p $aspera_bin_dir && \
  chmod 755 $aspera_bin_dir && \
  ascli conf ascp install && \
  ascli conf ascp info
# rootless execution
USER cliuser
# Default cwd when starting the container
WORKDIR /home/cliuser
ENTRYPOINT ["ascli"]
CMD ["help"]
