# frozen_string_literal: true

require 'aspera/log'
require 'json'
require 'securerandom'

module Aspera
  module Cli
    # Persist the state of asynchronous transfers on the local file system.
    #
    # Each entry is a JSON document identified by a `job_id` (UUID generated by ascli).
    # The underlying storage uses PersistencyFolder with the category prefix
    # +CATEGORY+ so all async-transfer files are grouped together and can be
    # garbage-collected independently.
    #
    # Schema of a stored entry:
    #   job_id            [String]  UUID generated by ascli (= the store key)
    #   agent_type        [String]  'desktop' | 'node' | 'connect' | 'transferd' | 'direct'
    #   transfer_id       [String]  Opaque ID returned by the agent's start_transfer
    #   agent_params      [Hash]    Agent-specific connection parameters for re-querying
    #   status            [String]  'running' | 'completed' | 'failed' | 'cancelled'
    #   bytes_transferred [Integer] Last known bytes transferred (0 if unknown)
    #   started_at        [String]  ISO-8601 timestamp
    #   ended_at          [String, nil] ISO-8601 timestamp once finished
    #   error             [String, nil] Error message when status == 'failed'
    class AsyncTransferStore
      CATEGORY = 'async_transfer_'
      private_constant :CATEGORY

      # @param persistency [PersistencyFolder]
      def initialize(persistency)
        @persistency = persistency
      end

      # Persist (create or update) an async transfer entry.
      # Keys whose name starts with '_' are in-process references (e.g. '_agent_ref')
      # and are intentionally excluded from the JSON serialization — at every nesting level.
      # @param job_id [String] the ascli-generated UUID
      # @param data   [Hash]   fields to store (will be JSON-serialised)
      def write(job_id, data)
        Aspera.assert_type(job_id, String){'job_id'}
        Aspera.assert_type(data, Hash){'data'}
        @persistency.put(store_key(job_id), JSON.generate(strip_internal_keys(data)))
        nil
      end

      # Read one entry.
      # @param job_id [String]
      # @return [Hash, nil] the stored data, or nil if not found
      def read(job_id)
        Aspera.assert_type(job_id, String){'job_id'}
        raw = @persistency.get(store_key(job_id))
        return if raw.nil?
        JSON.parse(raw)
      end

      # List all async transfer entries.
      # @return [Array<Hash>] each entry includes the +job_id+ field
      def list
        @persistency.current_items(CATEGORY).map do |key, raw|
          data = JSON.parse(raw)
          data['job_id'] ||= key.sub(CATEGORY, '')
          data
        end
      end

      # Delete one entry.
      # @param job_id [String]
      def delete(job_id)
        Aspera.assert_type(job_id, String){'job_id'}
        @persistency.delete(store_key(job_id))
        nil
      end

      private

      # Map a job_id to the PersistencyFolder key (includes category prefix).
      def store_key(job_id)
        "#{CATEGORY}#{job_id}"
      end

      # Recursively remove keys whose name starts with '_' from a Hash.
      # Such keys hold in-process Ruby object references (e.g. '_agent_ref') that
      # cannot be serialized to JSON and must never reach the file system.
      def strip_internal_keys(value)
        case value
        when Hash
          value.each_with_object({}) do |(k, v), h|
            h[k] = strip_internal_keys(v) unless k.to_s.start_with?('_')
          end
        when Array
          value.map{ |v| strip_internal_keys(v)}
        else
          value
        end
      end
    end
  end
end
