---
detectors:
  DuplicateMethodCall:
    exclude:
      - /Log.log/
  TooManyStatements:
    max_statements: 20
  FeatureEnvy:
    enabled: false
  BooleanParameter:
    enabled: false
  NilCheck:
    enabled: false
  TooManyConstants:
    enabled: false
