Style/MutableConstant:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Layout/AssignmentIndentation:
  Enabled: false
Layout/SpaceAfterComma:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceAroundBlockParameters:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Layout/MultilineHashBraceLayout:
  Enabled: false
Layout/SpaceAfterSemicolon:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/FirstArgumentIndentation:
  Enabled: false
Layout/MultilineArrayBraceLayout:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/PreferredHashMethods:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: false
Lint/EmptyClass: # (new in 1.3)
  Enabled: false
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: false
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: false
Style/NegatedWhile:
  Enabled: false
Security/Eval:
  Enabled: false
Style/StderrPuts:
  Enabled: false
