plugins:
  - rubocop-performance
inherit_gem:
  rubocop-shopify: rubocop.yml
inherit_from: .rubocop_todo.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - tmp/**/*
    - "lib/*_pb.rb"
Naming/MethodName:
  Enabled: true
  AllowedPatterns:
    - do_POST
    - do_GET
Naming/FileName:
  Exclude:
    - "**/*.gemspec"
    - "**/*_spec.rb"
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/LineLength:
  Max: 170
Layout/SpaceAfterComma:
  Enabled: true
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: true
  Max: 60
Metrics/ParameterLists:
  Max: 6
Metrics/BlockNesting:
  Max: 5
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
Style/BarePercentLiterals:
  EnforcedStyle: percent_q
Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_with_o
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma
Style/DateTime:
  Enabled: true
Style/ReturnNil:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma
#  Enabled: false
Style/Encoding:
  Enabled: true
Lint/RedundantCopDisableDirective:
  Enabled: false
