Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: no_space
Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: no_space
Layout/SpaceAroundBlockParameters:
  Enabled: true
  EnforcedStyleInsidePipes: no_space
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space
Layout/MultilineHashBraceLayout:
  Enabled: true
Layout/MultilineArrayBraceLayout:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false
Layout/MultilineArrayLineBreaks:
  Enabled: false
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstArrayElementLineBreak:
  Enabled: false
Layout/MultilineHashKeyLineBreaks:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/CommentedKeyword:
  Enabled: true
Style/NegatedIf:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true
Style/Documentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Layout/DotPosition:
  Enabled: true
Layout/AssignmentIndentation:
  Enabled: true
Layout/SpaceAroundOperators:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/LeadingCommentSpace:
  Enabled: true
Layout/FirstHashElementIndentation:
  Enabled: true
#Layout/EmptyLineAfterGuardClause:
#  Enabled: true
#Layout/HashAlignment:
#  Enabled: true
Layout/CaseIndentation:
  Enabled: true
Layout/SpaceAfterSemicolon:
  Enabled: true
Layout/FirstArgumentIndentation:
  Enabled: true
Style/WordArray:
  Enabled: true
  EnforcedStyle: percent
Style/SymbolArray:
  Enabled: true
  EnforcedStyle: percent
Style/PreferredHashMethods:
  Enabled: true
Style/CommentAnnotation:
  Enabled: true
Style/RegexpLiteral:
  Enabled: true
  AllowInnerSlashes: false
Style/Semicolon:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/SafeNavigation:
  Enabled: true
Style/RedundantBegin:
  Enabled: true
Layout/ArgumentAlignment:
  Enabled: true
Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented
Style/LambdaCall:
  Enabled: true
Style/MethodCallWithoutArgsParentheses:
  Enabled: true
Layout/EmptyLineAfterMagicComment:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: true
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NegatedWhile:
  Enabled: true
Security/Eval:
  Enabled: true
Naming/PredicateMethod:
  Enabled: false