NODE_PASS=Aspera123_
MY_CLIENT_ID=BMDiAWLP6g
MY_PRIVATE_KEY_FILE=$(TOOLCONFIGDIR)/filesapikey
#HSTS_ADDR=10.25.0.8
#FASPEX_ADDR=10.25.0.3
HSTS_ADDR=eudemo.asperademo.com
HSTS_SSH_URL=ssh://$(HSTS_ADDR):33001
HSTS_NODE_URL=https://$(HSTS_ADDR):9092
FASPEX_ADDR=$(HSTS_ADDR)
FASPEX_SSH_URL=ssh://$(FASPEX_ADDR):33001

TEST_SHARE=Upload
TEST_NODE_USER=node_asperaweb
TEST_NODE_PASS=Aspera123_

TEST_WORKFLOW_ID=894
