version: "0.2"
ignorePaths:
  - "**/*.pptx"
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - Aspera
  - FASP
  - ascli
  - ascmd
  - ascp
  - asyncadmin
  - asconfigurator
  - asnodeadmin
  - asuserdata
  - asperatransferd
  - aspshell
  - asctl
  - asession
  - watchd
  - watchfolderd
  - faspex
  - hsts
  - xfer
  - watchfolder
  - rubygems
  - containerimage
  - trspec
  - cliuser
  - asperaweb
  - docroot
  - cygwin
  - xferdir
  - xferfiles
  - automake
  - devel
  - gemdir
  - asperasoft
  - zmode
  - zuid
  - zgid
  - msys
  - prst
  - prsts
  - prstt
  - opprst
  - myserver
  - myvar
  - mykey
  - myfile
  - mytitle
  - myconf
  - mypreset
  - mylabel
  - mysample
  - myfilelist
  - mydir
  - myorg
  - mytemplate
  - myworkspace
  - mybucket
  - mysecret
  - myname
  - mysourcefile
  - mydestfolder
  - myext
  - myaccount
  - myaccesskey
  - myproxy
  - mypassvar
  - mycos
  - myblob
  - testfile
  - syncdir
  - lolo
  - kenji
  - incps
  - csvt
  - jsonpp
  - notif
  - privkeyfile
  - httpgw
  - trsdk
  - csear
  - pvcl
  - trapd
  - anacron
  - fpac
  - initdemo
  - samplefile
  - geminstadd
  - posix
  - userprofile
  - homedrive
  - homepath
  - localappdata
  - kbps
  - mbps
  - gbps
  - mebibyte
  - mebibit
  - gibibyte
  - gibibytes
  - apikey
  - faspe
  - pmax
  - ibmcloud
  - optipng
  - ffprobe
  - unoconv
  - ghostscript
  - mimemagic
  - freedesktop
  - inotify1
  - rubocop
  - multipass
  - rubyc
  - dockerhub
  - martinlaurent
  - noman
  - symb
  - shortval
  - cmdline
  - descr
  - optionval
  - tmpl
  - optparse
  - isatty
  - getpass
  - servlet
  - creds
  - tmpdir
  - trevents
  - retryable
  - nodeadmin
  - userdata
  - keychain
  - aslmcli
  - lprt
  - tspec
  - textify
  - readuntil
  - apfid
  - nodegen
  - dropboxes
  - paygo
  - xmlsimple
  - bfail # parameter
  - pkeypath # parameter
  - filelists # file part
  - demoserver # preset name
  - setx # cmd command
  - serban
  - imgtag # env var for docker ascli
  - loglevel # env var asession
  - filelist # env var asession
  - demoaspera
  - transferspec # tag in doc
  - usershome # tag in doc
  - optst # tag in makefile
  - bytescont # tag in progress bar
  - progressbar # ruby gem
  - trustpolicy # aws API
  - unshift # ruby
  - ibmaspera # AoC
  - asperafiles # AoC
  - csum # ascp arg
  - metafile # ascp arg
  - xattr # ascp arg
  - xattrs # ascp arg
  - datagram
  - asperanoded
  - sshfp # ascp
  - dnat # ascp
  - dnats # ascp
  - protobuf
  - entsrv
  - precalc
  - keepalive
  - transferd # ascli id
  - mlia
  - asperalm
import: []
enableFiletypes:
  - shellscript
ignoreRegExpList:
  - Email
  - >-
    /ftp:[^\s]*/g
patterns:
  - name: markdown_code_block
    pattern: |
      /
          ^(\s*`{3,}).*     # match the ```
          [\s\S]*?          # the block of code
          ^\1               # end of the block
      /gmx
languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - markdown_code_block
