version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - Aspera
  - FASP
  - ascli
  - ascmd
  - ascp
  - asyncadmin
  - asconfigurator
  - asnodeadmin
  - asuserdata
  - asperatransferd
  - aspshell
  - asctl
  - asession
  - watchd
  - watchfolderd
  - faspex
  - hsts
  - xfer
  - watchfolder
  - rubygems
  - containerimage
  - trspec
  - cliuser
  - asperaweb
  - docroot
  - cygwin
  - xferdir
  - xferfiles
  - automake
  - devel
  - gemdir
  - asperasoft
  - zmode
  - zuid
  - zgid
  - msys
  - prst
  - prsts
  - prstt
  - opprst
  - myserver
  - myvar
  - mykey
  - myfile
  - mytitle
  - myconf
  - mypreset
  - mylabel
  - mysample
  - myfilelist
  - mydir
  - myorg
  - mytemplate
  - myworkspace
  - mybucket
  - mysecret
  - myname
  - mysourcefile
  - mydestfolder
  - myext
  - myaccount
  - myaccesskey
  - myproxy
  - mypassvar
  - mycos
  - myblob
  - testfile
  - syncdir
  - lolo
  - kenji
  - incps
  - csvt
  - jsonpp
  - notif
  - privkeyfile
  - httpgw
  - trsdk
  - csear
  - pvcl
  - trapd
  - anacron
  - fpac
  - initdemo
  - samplefile
  - geminstadd
  - posix
  - userprofile
  - homedrive
  - homepath
  - localappdata
  - kbps
  - mbps
  - gbps
  - mebibyte
  - mebibit
  - gibibyte
  - gibibytes
  - apikey
  - faspe
  - pmax
  - ibmcloud
  - optipng
  - ffprobe
  - unoconv
  - ghostscript
  - mimemagic
  - freedesktop
  - inotify1
  - rubocop
  - multipass
  - rubyc
  - dockerhub
  - martinlaurent
  - noman
  - symb
  - shortval
  - cmdline
  - descr
  - optionval
  - tmpl
  - optparse
  - isatty
  - getpass
  - servlet
  - creds
  - tmpdir
  - trevents
  - retryable
import: []
enableFiletypes:
  - makefile
  - shellscript
