# Embedded Ruby template
# arg: arg_gem: specify a gemfile or a gem version
# arg: arg_sdk: specify a sdk file or empty (download from default url)
# Based on latest stable ruby : https://hub.docker.com/_/ruby
FROM ruby:latest
<% if arg_gem.end_with?('.gem') %>
# For beta gem is file, then copy it
COPY <%=arg_gem%> .
<% arg_gem=File.basename(arg_gem) %>
<% end %>
# Install gem (local or web) and optional gems
RUN \
  gem install grpc mimemagic <%=arg_gem%> && \
  useradd -m -u 1000 -s /bin/bash cliuser && \
  rm -f <%=arg_gem%>
# Ensures that the docker container always start with this user
USER cliuser
# The default dir when starting the docker container.
WORKDIR /home/cliuser
# set SDK location in container, must be outside /home/cliuser/.aspera/ascli which will be a volume
ENV ASCLI_SDK_FOLDER=/home/cliuser/.aspera/sdk
<% unless arg_sdk.empty? %>
# SDK file is available locally, then copy it
COPY <%=arg_sdk%> .
<% arg_sdk='--sdk-url=file:///'+File.basename(arg_sdk) %>
<% end %>
# Install SDK, create key files and check that ascp works
RUN \
  ascli conf ascp install <%=arg_sdk%> && \
  rm -f sdk.zip && \
  ascli conf ascp info
ENTRYPOINT ["ascli"]
CMD ["help"]
