# based on latest ruby
FROM ruby:latest
<%=arg_copy_gem%>
# install gem and optional gems
RUN gem install grpc mimemagic <%=arg_gem%> && \
  useradd -m -u 1000 -s /bin/bash cliuser && \
  rm -f <%=arg_gem%>
# Ensures that the docker container always start with this user
USER cliuser
# The default dir when starting the docker container.
WORKDIR /home/cliuser
# SDK
<%=arg_copy_sdk%>
# install SDK, create key files and check that ascp works
RUN \
  ascli conf ascp install <%=arg_sdk%> && \
  rm -f sdk.zip && \
  ascli conf ascp info
ENTRYPOINT ["ascli"]
CMD ["help"]
