#!/bin/bash

set -e

if test $# -ne 5; then
    echo "Usage: $0 <CLI_EXECUTABLE> <CLI_PATH> <GEM_NAME> <GEM_VERSION> <DIR_TMP>" 1>&2
    exit 1
fi

CLI_EXECUTABLE=$1
CLI_PATH=$(realpath $2)
GEM_NAME=$3
GEM_VERSION=$4
DIR_TMP=$(realpath $5)

local=true

echo "Building: $(basename $CLI_EXECUTABLE)"

# tebako compilation
tebako_env=$DIR_TMP/tebako-env
# project files (gem)
tebako_root=$DIR_TMP/tebako-root
#
entry_point=$(basename $CLI_PATH)

if $local;then
    gem install tebako
    mkdir -p $tebako_env $tebako_root
    (cd $tebako_root && gem fetch $GEM_NAME:$GEM_VERSION)
    case $(uname -s) in
    Darwin)
        brew update
        brew install bison flex binutils libffi double-conversion boost jemalloc fmt glog gnu-sed bash
        brew install pkg-config gdbm zlib ncurses libevent libsodium lz4 xz libyaml openssl@3
        export PATH=/opt/homebrew/opt/flex/bin:/opt/homebrew/opt/bison/bin:$(echo $PATH|tr : \\n|grep -v /binutils/|tr \\n :)
        ;;
    Linux)
        #tebako_root=/mnt/w
        #tebako press --root=$tebako_root --entry-point=ascli --output=$tebako_root/ascli.exe --Ruby=3.3.3 
        #tebako_prefix="podman run -it --rm -v $PWD:$tebako_root ghcr.io/tamatebako/tebako-ubuntu-20.04:0.8.6"
        #tebako_opts=--patchelf
        ;;
    *)
        echo "This OS is not supported." >&2
        exit 1
        ;;
    esac
    exec tebako press --root=$tebako_root --entry-point=$entry_point --output=$CLI_EXECUTABLE --prefix=$tebako_env
else
    # https://github.com/you54f/ruby-packer
    # https://github.com/YOU54F/ruby-packer/releases
    set -e
    FOLDER="$(dirname $0)/../tmp"
    RUBYC="$FOLDER/rubyc"
    if test ! -e "$RUBYC"; then
        mkdir -p "$FOLDER"
        case $(uname -sm|tr ' ' -) in
            Darwin-arm64)
                curl -L https://github.com/YOU54F/ruby-packer/releases/download/rel-20230812/rubyc-Darwin-arm64.tar.gz | tar -xz -C "$FOLDER"
                mv "$FOLDER/rubyc-Darwin-arm64" "$RUBYC"
                ;;
            Linux-x86_64)
                curl -L https://github.com/YOU54F/ruby-packer/releases/download/rel-20230812/rubyc-Linux-x86_64.tar.gz | tar -xz -C "$FOLDER"
                mv "$FOLDER/rubyc-Linux-x86_64" "$RUBYC"
                ;;
            *)
                echo "This architecture is not supported." >&2
                exit 1
                ;;
        esac
    fi
    exec "$RUBYC" -o "$CLI_EXECUTABLE" "$CLI_PATH"
fi
