#!/usr/bin/env bash
# set env var image to specify another docker image
# set env var version to specify another image version
# set env var docker_args to add options to docker run
: ${image:=martinlaurent/ascli}
# by default take latest version
: ${version:=latest}
: ${docker:=docker}
: ${imgtag=$image:$version}
# transform var into array
add_dock_args=( $docker_args )
# same location as in Dockerfile: main config folder for ascli in container
ascli_home_container=/home/cliuser/.aspera/ascli
# set default location for config folder on host if necessary
: ${ASCLI_HOME:=$HOME/.aspera/ascli}
if test ! -d $ASCLI_HOME;then
	echo "creating foder: $ASCLI_HOME"
	# create it if necessary to allow mounting the volume in container
	mkdir -p "$ASCLI_HOME"
fi
exec $docker run \
--rm \
--tty \
--interactive \
--volume "$ASCLI_HOME:$ascli_home_container" \
"${add_dock_args[@]}" \
$imgtag \
ascli "$@"
