#!/usr/bin/env bash
: ${image:=martinlaurent/ascli}
# by default take latest version
: ${version:=latest}
imgtag=$image:$version
# same location as in Dockerfile: generic top folder for apps
appdir=/usr/src/app
# same location as in Dockerfile: main config folder for ascli in container
ascli_home_container=${appdir}/config
# convenience: special argument to install the image
case "$1" in install) docker pull $imgtag; exit 0; esac
# set default location for config folder on host if necessary
: ${ASCLI_HOME:=$HOME/.aspera/ascli}
if test ! -d $ASCLI_HOME;then
	echo "creating foder: $ASCLI_HOME"
	# create it if necessary to allow mounting the volume in container
	mkdir -p "$ASCLI_HOME"
fi
exec docker run \
--rm \
--tty \
--interactive \
--env ASCLI_HOME="$ascli_home_container" \
--volume "$ASCLI_HOME:$ascli_home_container" \
$imgtag \
ascli "$@"
