# frozen_string_literal: true

require_relative '../build/lib/build_tools'
require 'aspera/uri_reader'
require 'aspera/rest'
require 'aspera/assert'
require 'json'
require 'yaml'
include BuildTools
include Paths

namespace :tools do
  desc 'Show changes since latest tag'
  task changes: [] do
    latest_tag = run(*%w[git describe --tags --abbrev=0], mode: :capture).first.chomp
    log.info("Changes since #{latest_tag}")
    run('git', 'log', "#{latest_tag}..HEAD", '--oneline', env: {'PAGER'=>''})
  end
  # https://github.com/Yelp/detect-secrets
  desc 'Init scan of secrets'
  task scan_init: [] do
    run('detect-secrets', 'scan', '--exclude-files', '^.secrets.baseline$', '--exclude-secrets', '_here_', '--exclude-secrets', '^my_', '--exclude-secrets', '^your ', '--exclude-secrets', 'demoaspera')
  end
  desc 'Scan secrets'
  task scan: [] do
    run('detect-secrets', 'scan', '--baseline', '.secrets.baseline')
  end
  desc 'Rubocop'
  task rubocop: [] do
    run('rubocop', LIB)
  end
  desc 'Reek'
  task reek: [] do
    run('reek', '-c', TOP / '.reek.yml')
  end
  desc 'Semgrep'
  task semgrep: [] do
    run('semgrep', 'scan', '--config', 'auto')
  end

  desc 'Remove all installed gems'
  task clean_gems: [] do
    gems_dir = File.join(Gem.dir, 'gems')
    if Dir.exist?(gems_dir) && !Dir.empty?(gems_dir)
      gem_names =
        Dir.children(gems_dir)
          .map{ |d| d.sub(/-[0-9].*$/, '')}
          .uniq
          .sort
      run('gem', 'uninstall', '-a', '-x', '-I', *gem_names)
    end
    GEMFILE_LOCK.delete
    run('gem', 'install', 'bundler')
  end

  PROTO_PATH = TMP / 'protos'
  GRPC_DEST = LIB
  desc 'Build Transfer SDK stub from proto'
  task grpc: [] do
    PROTO_PATH.mkpath
    download_proto_file(PROTO_PATH)
    run('grpc_tools_ruby_protoc', "--proto_path=#{PROTO_PATH}", "--ruby_out=#{GRPC_DEST}", "--grpc_out=#{GRPC_DEST}", PROTO_PATH / 'transferd.proto')
  end

  task :check_signature do
    run('gem', 'specification', built_gem_file, 'signing_key', 'cert_chain', 'version')
  end

  desc 'Show gem build version'
  task :version do
    puts BuildTools.build_version
  end

  desc 'Prepare beta version'
  task :version_override, [:version] do |_t, args|
    Aspera.assert(!args[:version].to_s.empty?){'Version argument is required for beta task'}
    OVERRIDE_VERSION_FILE.write(args[:version])
    puts("Beta version set to: #{BuildTools.build_version}")
  end

  desc 'Download OpenAPI schemas from GitHub'
  task :openapi do
    config_file = TOP / 'docs' / 'openapi_sources.yaml'
    Aspera.assert(File.exist?(config_file), "Configuration file not found: #{config_file}")
    config = YAML.load_file(config_file)
    Aspera.assert(config['schemas'], "No 'schemas' section found in configuration file")
    config['schemas'].each do |schema|
      url = schema['url']
      destination = TOP / schema['destination']
      log.info("Downloading: #{url}")
      log.info("Destination: #{destination}")
      begin
        # Download the file content using UriReader
        content = Aspera::UriReader.read(url)
        # Add header comment with source URL and warning
        header = <<~HEADER
          # DO NOT EDIT THIS FILE MANUALLY
          # This file is automatically downloaded from:
          # #{url}
          # Use 'rake tools:openapi' to update this file

        HEADER
        # Write the header and content to the destination file
        destination.write(header + content)
      end
    end
    log.info('All OpenAPI schemas downloaded successfully')
  end

  desc 'Update Ruby version in GitHub Actions workflows to the latest stable release'
  task :update_ruby do
    # Source of truth: the version list used by ruby/setup-ruby itself.
    # Only plain "X.Y.Z" entries are considered stable (no -preview, -rc, etc.).
    versions_url = 'https://raw.githubusercontent.com/ruby/setup-ruby/refs/heads/master/ruby-builder-versions.json'
    log.info("Fetching Ruby versions from: #{versions_url}")
    raw = Aspera::Rest.new(base_url: versions_url, redirect_max: 3).read(nil)
    data = raw.is_a?(String) ? JSON.parse(raw) : raw

    # All stable CRuby releases as [major, minor, patch] integer tuples.
    stable_versions = data['ruby']
      .filter_map do |v|
        m = v.match(/\A(\d+)\.(\d+)\.(\d+)\z/)
        m ? [m[1].to_i, m[2].to_i, m[3].to_i] : nil
      end
    raise 'No stable Ruby versions found' if stable_versions.empty?

    # Minimum supported version from the gemspec (e.g. ">= 3.1" → [3, 1]).
    gemspec_min = Paths::GEMSPEC.read[/required_ruby_version\s*=\s*['"]>=\s*(\d+\.\d+)['"]/, 1]
    raise 'Could not read required_ruby_version from gemspec' unless gemspec_min
    min_ver = gemspec_min.split('.').map(&:to_i)
    log.info("Minimum Ruby version (from gemspec): #{gemspec_min}")

    # Latest overall release — used by fixed ruby-version: "X.Y.Z" fields.
    latest_str = stable_versions.max.join('.')
    log.info("Latest stable Ruby version: #{latest_str}")

    # One "X.Y" entry per minor line, from min_ver up to latest, plus jruby.
    # setup-ruby resolves "X.Y" to the latest patch automatically.
    minor_lines = stable_versions
      .map{ |maj, min, _patch| [maj, min] }
      .uniq
      .sort
      .select{ |ver| (ver <=> min_ver) >= 0 }
      .map{ |maj, min| "#{maj}.#{min}" }
    test_matrix = minor_lines + ['jruby']
    log.info("Test matrix: #{test_matrix.inspect}")

    workflows_dir = TOP / '.github' / 'workflows'
    updated = []
    workflows_dir.glob('*.yml').sort.each do |workflow_file|
      content = workflow_file.read
      new_content = content.dup

      # 1. Fixed ruby-version: "X.Y.Z" fields (deploy, release, cert-renew, yank).
      new_content.gsub!(/(?<=ruby-version:\s)(["'])\d+\.\d+\.\d+\1/) do
        "#{Regexp.last_match(1)}#{latest_str}#{Regexp.last_match(1)}"
      end

      # 2. Matrix list in test.yml:  ruby: ["X.Y", ..., "jruby"]
      new_content.gsub!(/(?<=ruby: )\["[\d.]+"(?:, "(?:[\d.]+|jruby)")*\]/) do
        '[' + test_matrix.map{ |v| %("#{v}") }.join(', ') + ']'
      end

      if new_content != content
        workflow_file.write(new_content)
        updated << workflow_file.basename.to_s
        log.info("Updated: #{workflow_file.relative_path_from(TOP)}")
      end
    end

    if updated.empty?
      log.info('All workflow files already use the latest Ruby version — nothing to update.')
    else
      log.info("Updated #{updated.size} workflow file(s): #{updated.join(', ')}")
    end
  end
end
