# Private data for test systems
# Do not share
# fill this file and place in folder "local"

CF_COMMON_PASS=_value_here_
CF_AOC1_CLIENT_ID=_value_here_
CF_PRIVATE_KEY_FILE=_value_here_
#CF_HSTS1_ADDR=_value_here_
CF_HSTS1_ADDR=_value_here_
CF_HSTS_SSH_URL=_value_here_
CF_HSTS_SSH_USER=_value_here_
CF_HSTS_SSH_PASS=_value_here_
CF_HSTS_NODE_URL=_value_here_
CF_HSTS_NODE_USER=_value_here_
CF_HSTS_NODE_PASS=_value_here_
CF_FASPEX_ADDR=_value_here_
CF_FASPEX_URL=_value_here_
CF_FASPEX_SSH_URL=_value_here_
CF_FASPEX_PUBLINK_RECV_PACKAGE=_value_here_
CF_FASPEX_PUBLINK_SEND_DROPBOX=_value_here_
CF_FASPEX_PUBLINK_SEND_TO_USER=_value_here_
CF_HSTS_FOLDER_UPLOAD=_value_here_

CF_SHARES_UPLOAD=_value_here_

# used in aspera_spec.rb
export CF_HSTS_SSH_URL CF_HSTS_SSH_USER CF_HSTS_SSH_PASS

# Incoming asset processing
CF_WORKFLOW_ID=_value_here_

CF_AOC_PUBLINK_RECV_PACKAGE=_value_here_
CF_AOC_PUBLINK_SEND_DROPBOX=_value_here_
CF_AOC_PUBLINK_SEND_USER=_value_here_
CF_AOC_PUBLINK_FOLDER=_value_here_
CF_AOC_WS_SH_BX=_value_here_
CF_AOC_SH_BX=_value_here_

CF_SAMPLE_FILENAME=_value_here_
CF_SAMPLE_FILEPATH=_value_here_

CF_AWS_ACCESS_KEY=_value_here_
CF_AWS_SECRET_KEY=_value_here_
CF_AWS_BUCKET=_value_here_
CF_AWS_REGION=_value_here_

CF_ICOS_API_KEY=_value_here_
CF_ICOS_BUCKET=_value_here_
CF_ICOS_AK_ID=_value_here_
CF_ICOS_SECRET_AK=_value_here_
CF_ICOS_REGION=_value_here_
CF_ICOS_CREDS_FILE=_value_here_

